---
title: "Embedded Shiny App"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(shiny)
d = readr::read_csv(here::here("data/weather.csv"))

d_vars = d %>%
  select(where(is.numeric)) %>%
  names()
```

## Shiny App

```{r}
#| echo: false

fluidRow(
  selectInput(
    "state", "Select a state",
    choices = sort(unique(d$state))
  ),
  selectInput(
    "city", "Select a city",
    choices = c(),
    multiple = TRUE
  ),
  selectInput(
    "var", "Select a variable",
    choices = d_vars, selected = "temperature"
  )
)
```

### Plot

```{r}
#| echo: false
plotOutput("plot")
```

### Table

```{r}
#| echo: false
tableOutput("minmax")
```


```{r}
#| echo: FALSE
#| context: server
d_city = reactive({
  req(input$city)
  d %>%
    filter(city %in% input$city)
})

observe({
  cities = d %>%
    filter(state %in% input$state) %>%
    pull(city) %>%
    unique() %>%
    sort()
  
  updateSelectInput(
    inputId = "city", 
    choices = cities
  )
})

output$plot = renderPlot({
  d_city() %>%
    ggplot(aes(x=time, y=.data[[input$var]], color=city)) +
    ggtitle(input$var) +
    geom_line()
})

output$minmax = renderTable({
  d_city() %>%
    mutate(
      day = lubridate::wday(time, label = TRUE, abbr = FALSE),
      date = as.character(lubridate::date(time))
    ) %>%
    group_by(date, day) %>%
    summarize(
      `min` = min(.data[[input$var]]),
      `max` = max(.data[[input$var]]),
      .groups = "drop"
    )
})
```
