---
title: "Widgets"
format: html
server: shiny
execute:
  echo: true
---

## Sliders

```{r slider}
#| eval: false
sliderInput(inputId="slider", label="Slider", 
            min=0, max=10, value=5)
```

::: columns
::: {.column width="50%"}
```{r slider_real}
#| echo: false
sliderInput(inputId="slider", label="Slider", 
            min=0, max=10, value=5)
```
:::

::: {.column width="50%"}
```{r slider_out1}
#| echo: false
verbatimTextOutput("slider_out")
```

```{r slider_out2}
#| echo: false
#| context: server
output$slider_out = renderPrint({
  input$slider
})
```
:::
:::

<br/>

```{r}
#| eval: false
sliderInput(inputId="sl_range", label="Slider Range", 
            min=0, max=10, value=c(3,7))
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
sliderInput(inputId="sl_range", label="Slider Range", 
            min=0, max=10, value=c(3,7))
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("sl_range_out")
```

```{r}
#| echo: false
#| context: server
output$sl_range_out = renderPrint({
  input$sl_range
})
```
:::
:::

## Text & Numeric

```{r}
#| eval: false
textInput(inputId="text", label="Text", placeholder = "Enter your text")
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
textInput(inputId="text", label="Text Input", placeholder = "Enter your text")
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("text_out")
```

```{r}
#| echo: false
#| context: server
output$text_out = renderPrint({
  input$text
})
```
:::
:::

<br/>

```{r}
#| eval: false
numericInput(inputId="numeric", label="Numeric Input",
             min=0, max=10, value=5)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
numericInput(inputId="numeric", label="Numeric Input", min=0, max=10, value=5, width = "300px")
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("numeric_out")
```

```{r}
#| echo: false
#| context: server
output$numeric_out = renderPrint({
  input$numeric
})
```
:::
:::

## Checkboxes

```{r}
#| eval: false
checkboxInput(inputId="checkbox", label="Checkbox", value=FALSE)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
checkboxInput(inputId="checkbox", label="Checkbox", value=FALSE)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("checkbox_out")
```

```{r}
#| echo: false
#| context: server
output$checkbox_out = renderPrint({
  input$checkbox
})
```
:::
:::

<br/>

```{r}
#| eval: false
checkboxGroupInput("checkbox_group", "Checkbox Group",
                   choices = list("Option 1" = 1,
                                  "Option 2" = 2,
                                  "Option 3" = 3,
                                  "Other"    = "other"),
                   selected = c(1,4))
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
checkboxGroupInput("checkbox_group", "Checkbox Group",
                   choices = list("Option 1" = 1,
                                  "Option 2" = 2,
                                  "Option 3" = 3,
                                  "Other"    = "other"),
                   selected = c(1,4))
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("cb_grp_out")
```

```{r}
#| echo: false
#| context: server
output$cb_grp_out = renderPrint({
  input$checkbox_group
})
```
:::
:::

## Radio buttons

```{r}
#| eval: false
radioButtons(
  inputId="radiobutton", label="Radio buttons",
  choices = list(
    "Option 1" = 1,
    "Option 2" = 2,
    "Option 3" = 3,
    "Other"    = "other"
  ),
  selected = 2
)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
radioButtons(
  inputId="radiobutton", label="Radio buttons",
  choices = list(
    "Option 1" = 1,
    "Option 2" = 2,
    "Option 3" = 3,
    "Other"    = "other"
  ),
  selected = 2
)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("radiobutton_out")
```

```{r}
#| echo: false
#| context: server
output$radiobutton_out = renderPrint({
  input$radiobutton
})
```
:::
:::

## Select Input

```{r}
#| eval: false
selectInput(
  inputId="select", label="Select Input",
  choices = list(
    "Option 1" = 1,
    "Option 2" = 2,
    "Option 3" = 3,
    "Other"    = "other"
  ),
  selected = 2
)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
selectInput(
  inputId="select", label="Select Input",
  choices = list(
    "Option 1" = 1,
    "Option 2" = 2,
    "Option 3" = 3,
    "Other"    = "other"
  ),
  selected = 2
)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("select_out")
```

```{r}
#| echo: false
#| context: server
output$select_out = renderPrint({
  input$select
})
```
:::
:::

## (Multi) Select Input

```{r}
#| eval: false
selectInput(
  inputId="mselect", label="Multiselect Input",
  choices = setNames(state.abb, state.name),
  selected = "MD",
  multiple = TRUE
)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
selectInput(
  inputId="mselect", label="Multiselect Input",
  choices = setNames(state.abb, state.name),
  selected = "MD",
  multiple = TRUE
)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("mselect_out")
```

```{r}
#| echo: false
#| context: server
output$mselect_out = renderPrint({
  input$mselect
})
```
:::
:::

## Action buttons & links

```{r}
#| eval: false
actionButton(inputId="action", label="Click me!")
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
actionButton(inputId="action", label="Click me!")
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("action_out")
```

```{r}
#| echo: false
#| context: server
output$action_out = renderPrint({
  input$action
})
```
:::
:::

<br/>

```{r}
#| eval: false
actionLink(inputId="actionlink", label="Click me!")
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
actionLink(inputId="actionlink", label="Click me!")
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("actionlink_out")
```

```{r}
#| echo: false
#| context: server

output$actionlink_out = renderPrint({
  input$actionlink
})
```
:::
:::


## Date inputs

```{r}
#| eval: false
dateRangeInput(
  inputId="date", label="When did you arrive?",
  value = Sys.Date(),
  min = Sys.Date()-14,
  max = Sys.Date(),
  daysofweekdisabled = c(0,6)
)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
dateInput(
  inputId="date", label="When did you arrive?",
  value = Sys.Date(),
  min = Sys.Date()-14,
  max = Sys.Date(),
  daysofweekdisabled = c(0,6)
)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("date_out")
```

```{r}
#| echo: false
#| context: server
output$date_out = renderPrint({
  input$date
})
```
:::
:::

<br/>

```{r}
#| eval: false
dateRangeInput(
  inputId = "daterange", 
  label = "How long will you be in DC?",
  start = "2022/07/25",
  end = "2022/07/28",
  min = Sys.Date()-14,
  max = Sys.Date()+14
)
```

::: columns
::: {.column width="50%"}
```{r}
#| echo: false
dateRangeInput(
  inputId = "daterange", 
  label = "How long will you be in DC?",
  start = "2022/07/25",
  end = "2022/07/28",
  min = Sys.Date()-14,
  max = Sys.Date()+14
)
```
:::

::: {.column width="50%"}
```{r}
#| echo: false
verbatimTextOutput("daterange_out")
```

```{r}
#| echo: false
#| context: server
output$daterange_out = renderPrint({
  input$daterange
})
```
:::
:::
